"""cascade delete assignments when user deleted

Revision ID: 3f2311fe0496
Revises: d7dfc5eef772
Create Date: 2026-05-03 19:25:04.807483
"""

from alembic import op
import sqlalchemy as sa


revision = '3f2311fe0496'
down_revision = 'd7dfc5eef772'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Remove orphaned assignments left over from prior SET NULL behaviour
    op.execute("DELETE FROM assignments WHERE user_id IS NULL")
    op.alter_column('assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('assignments_user_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_user_id_fkey', 'assignments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
