"""initial schema

Revision ID: a9e6e26c7ef9
Revises: 
Create Date: 2026-05-02 15:17:22.400365
"""

from alembic import op
import sqlalchemy as sa


revision = 'a9e6e26c7ef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignments_task_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_task_id_fkey', 'assignments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
