"""make user FKs nullable with SET NULL

Revision ID: d7dfc5eef772
Revises: 444dbeb1c73a
Create Date: 2026-05-03 19:16:56.660973
"""

from alembic import op
import sqlalchemy as sa


revision = 'd7dfc5eef772'
down_revision = '444dbeb1c73a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('assignments_user_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('events_created_by_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('feedback_user_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('projects_created_by_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_created_by_fkey', 'projects', 'users', ['created_by'], ['id'])
    op.alter_column('projects', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_user_id_fkey', 'feedback', 'users', ['user_id'], ['id'])
    op.alter_column('feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_created_by_fkey', 'events', 'users', ['created_by'], ['id'])
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_user_id_fkey', 'assignments', 'users', ['user_id'], ['id'])
    op.alter_column('assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
